<a href="https://colab.research.google.com/github/Manireddy69/Data-science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
df = np.array([[1,2,3,4],
               [5,6,7,8]])

In [20]:
df[:, 0] #columns(starting from index = 0)
df[1] #Rows
df[0][0]  #[Row][column]

np.int64(1)

In [23]:
b2 = df.copy() # FULL copy of an array
df[0] = [1,2,4,5]

array([[1, 2, 4, 5],
       [5, 6, 7, 8]])

In [38]:
one = np.ones((3,3), dtype= int)
identity = np.eye(3, dtype = int)

In [41]:
np.array((identity/ one), dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
df = np.random.RandomState(42).randint(1,10, (3,3)) #Randomstate(42) is to keep elements fixed
df

array([[7, 4, 8],
       [5, 7, 3],
       [7, 8, 5]])

In [52]:
np.sum(df,axis = 0) # sum of each column
np.sum(df, axis = 1) # sum of each row

array([19, 15, 20])

In [60]:
df = np.random.RandomState(42).randint(10,size = 5)
df

array([6, 3, 7, 4, 6])

In [66]:
df.max()
df.min()
df.mean()
df.sum()

np.int64(26)

In [ ]:
#then how does this works on 2-d array

In [68]:
df = np.random.RandomState(42).randint(1,10,(2,2))
df

array([[7, 4],
       [8, 5]])

In [72]:
df.max()
df.mean()
df.max()
df.sum()   # works same as 1-d array

np.int64(24)

In [78]:
df = np.array([1,1,2,2,2,3,3,4,5,6,7,7,7,8,8])
np.unique(df, return_index = True) #gives unique elements & indexes of it.

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 0,  2,  5,  7,  8,  9, 10, 13]))

In [80]:
np.unique(df, return_counts = True) #same: give unique and counts of the each element

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([2, 3, 2, 1, 1, 1, 3, 2]))

In [16]:
m = np.random.RandomState(42).randint(1,10, size =(2,3))

In [90]:
m2 = np.arange(6).reshape(2,3) ## Becareful with arange(num) takes only #of elements in the matrix.

In [3]:
import numpy as np
d = np.array([[1,2,3,3,4],
              [1,2,3,4,3]])

In [20]:
np.shape(d)

(2, 5)

In [6]:
np.save('first',d) # Saves the array 'd' to 'first.npy' in the Colab environment.

In [11]:
b = np.load('first.npy')

In [12]:
#even we can convert numpy array into Dataframe
import pandas as pd

In [24]:
df = pd.DataFrame(d, index = list(range(1,3)), dtype= int, columns= list(range(1,6)))
df

   1  2  3  4  5
1  1  2  3  3  4
2  1  2  3  4  3

1    2
2    2
Name: 2, dtype: int64